authors:
  Mukesh:
    name: Mukeshraj Mahendran
    description: Creator
    avatar: https://raw.githubusercontent.com/MUKESHRAJMAHENDRAN/knowledge/main/images/Mukesh.jpeg

plugins:
  - search
  - blog
  - meta